name: negation_without_space
on: [pull_request, push]
jobs:
  negation_without_space:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ !contains('Hello world', 'moon') }}
        run: echo "This fails but it has no syntax highlighting."
